PRAGMA defer_foreign_keys=TRUE;
CREATE TABLE [FluentAPIs] ("Name" text PRIMARY KEY,"API_KEY" text,"AFFILIATE_ID" text);
INSERT INTO FluentAPIs VALUES('Brian','hFct58Jru5Y5cPlP8VGq8Q','207744');
INSERT INTO FluentAPIs VALUES('Max','k1Cz6mbXFpb2OrxVgF35Cw','208253');
CREATE TABLE [Users] ("ID" integer PRIMARY KEY,"Name" text,"Username" text,"Password" text,"Permissions" text);
INSERT INTO Users VALUES(0,'Default','Admin','xzM^T1qtHR1d%T1@3hUj5P^Zhr^%FVusI','All');
CREATE TABLE [BooleanSettings] ("Name" text PRIMARY KEY,"IsTrue" text DEFAULT false);
INSERT INTO BooleanSettings VALUES('IsTikTokTrafficRouting','true');
CREATE TABLE [Templates] ("Name" text PRIMARY KEY,"Type" text,"Value" text);
CREATE TABLE [TemplateTypes] ("Type" text PRIMARY KEY);
INSERT INTO TemplateTypes VALUES('HTML');
INSERT INTO TemplateTypes VALUES('Google Form');
CREATE TABLE [Campaigns] ("Name" text,"Domain" text,"IsActive" text DEFAULT true,"IsTikTokRouting" text DEFAULT true,"TemplateName" text,"AffiliateLink" text,"AllowedRegions" text,"WhiteHatMode" text,"WhiteHatValue" text);
CREATE TABLE [InitialDomains] ("Redirect" text PRIMARY KEY);
CREATE TABLE [RedirectDomains] ("Domain" text);
CREATE TABLE [UserPermissions] ("Name" text PRIMARY KEY);
INSERT INTO UserPermissions VALUES('All');
INSERT INTO UserPermissions VALUES('View Campaigns');
INSERT INTO UserPermissions VALUES('Edit Campaigns');
INSERT INTO UserPermissions VALUES('View Metrics');
INSERT INTO UserPermissions VALUES('View Templates');
INSERT INTO UserPermissions VALUES('Edit Templates');
INSERT INTO UserPermissions VALUES('View Settings');
INSERT INTO UserPermissions VALUES('Edit Settings');
